### ISSUE TITLE
Console not reloading function file on save

### ISSUE THREAD

**Issue by mtyrlik** [StructuredDataLLC/Basic-Excel-R-Toolkit#160]
Hello everyone, I am having an issue described below:

Installation info:
Windows 10 63 bit
R 3.5.0
MS Excel Version 1811 (Build 11029.20079 Microsoft Store)
BERT2.4.4

Installation Note Note:
When I installed BERT, it did not add to the add-ins list automatically, I added both the actual BERT32.xll file. The ribbon icon did not display until I ALSO added BERTRibbon2x86.xll as a COM add-in.

Issue Description: I can open the console, but whenever I try to save (either file->save or ctrl+S), the BERT console does not reload the file. I see no new messages in the console and the functions do not appear in the excel functions menu.

I also have another issue with the ribbon menu. I am not certain if these are related so I created a separate issue here: https://github.com/sdllc/Basic-Excel-R-Toolkit/issues/159

Thanks a lot for your help.

**Comment by malcook** [comment]
If your setup is like mine, with 
 - a home directory on a network share
 - you take the default location for installing BERT (which corresponds to %localappdata%)

then I expect the following will work for you:

First, create a windows system environment variable.  This seems not to be happening by the installer.

BERT_HOME=%localappdata%/BERT2

For me, that got the BERT add-in starting up.  Now to fix the configuration:

Change the R stanza of BERT preferences as follows

    "R": {
      "home": "%bert_home%\\R-3.5.0", 
      "lib": "%bert_home%\\R-3.5.0\\library"
    },

And change the 

    "functionsDirectory": "%homeshare%\\My Documents\\BERT2\\functions" 

And restart Excel.

That got me going.  Nothing further needed.

If this works, the devs should fix the installer/default prefs.

Or my thinking about what to expect, but, it works for me.

**Comment by mtyrlik** [comment]
Thanks a lot for your reply.

I set the environment variable as you advised and it did not help with the error message. It still appears every time I restart office.

I do not have a homeshare setup, but I do have a secondary drive (D) on m computer. The Documents folder, including the folder with the BERT2 function folders. The actual installation is on the primary (C) drive. How would I format this second line to redirect it to D>user>documents>bert2>…?

**Comment by mtyrlik** [comment]
I just discovered another related issue. I am unable to save the preference file. When I open it in the BERT editor, it does not save regardless of whether I try ctrl+S or file>Save As.

It still does say "Preferences OK" on the bottom

**Comment by malcook** [comment]
Apologies if I misguided you, but I still expect the solution to your dilemma will be the correct setting of BERT_HOME and other file paths particular to your installation.

Did you check to see if BERT_HOME was set already before following my advice?  If so, what was it?  If not, did you wind up setting it to whatever folder holds your bert-config.json file.  In my case that turned out to be `C:\Users\mec\AppData\Local\BERT2 `which happens to be `%localappdata%\BERT2`.  If your is different, just hard-wire it for now.  Whatever you set it to, confirm it is correct as follows: 

- performing WindowsKey-R > "%BERT_HOME%" > <Enter> 

should open a file system explorer windows on the BERT_HOME directory containing the bert-config.json file.  If it does not, then the environment is incorrect and don't expect BERT to fully function correctly.

I'm not positive I understand what you mean by "second line".  If you mean the functionsDirectory line, my advice is to try this:

Make sure functionsDirectory is pointing to `D:\\user\\documents\\bert2\\functions` - I think the double backslashes may be required, and I am surprised that user is not plural, and I expect the case you provided may be incorrect (you may really want `D:\\Users\\Documents\\BERT2\\functions`).

NB - you do NOT want it pointing to the \\files directory inside of BERT_HOME.  If you are working in this \\files directory I think you are doing "the wrong thing".

My guess is the variety of locations for storing preferences and default files is challenging to write installers for.  But getting those few paths set correctly and all should hang together for you.  I think there are a bunch of open BERT issues which extend from misalignment of these system variables and paths.  Good luck.

**Comment by mtyrlik** [comment]
Dear malcook,

Thank you very much for your help. I have been able to resolve this issue with your instructions. My functions now reload on save and and load to excel functions menu.

Even though I previously changed the environment variable it did not actually load until I rebooted the system.

Some process also keeps my bert-config.json file loaded even when bert and excel are shut down. I had to edit the file directly with sublime text after reboot instead of through the BERT console.

The other Issue I am experiencing (https://github.com/sdllc/Basic-Excel-R-Toolkit/issues/159) still persists.
